# Generated by Django 5.1.6 on 2025-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('kurti', 'Kurti'), ('WC', 'Western Cloths'), ('B', 'Beauty')], max_length=10),
        ),
    ]
