# Generated by Django 5.1.6 on 2025-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('kurti', 'Kurti'), ('Western Cloths', 'Western Cloths'), ('B', 'Beauty')], max_length=20),
        ),
    ]
