# Generated by Django 5.1.6 on 2025-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_payment_method_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'paypal'), ('cod', 'Cash on Delivery')], default='stripe', max_length=10),
        ),
    ]
