# Generated by Django 5.1.6 on 2025-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
